DATA:
  ROOT: ""  
  TRAIN_FILE: "labels/all_train_list.txt"  
  VAL_FILE: "labels/tvsum_train_list.txt"    
  LABEL_LIST: "labels/tvsum_multihot_labels.npy"  
  NUM_FRAMES: 16     # 【瘦身】从32降到16，大幅减少序列长度带来的显存爆炸
  NUM_CLASSES: 45    
  FRAME_INTERVAL: 2  
MODEL:
  ARCH: ViT-B/32
  PRETRAINED: ""     
TRAIN:
  BATCH_SIZE: 1      # 【瘦身】端到端读视频，Batch Size 设为 1
  BATCH_SIZE_UMIL: 1 # 【瘦身】同上
  EPOCHS: 50
  OPT_LEVEL: O1      # 使用原生 AMP 时，O1 对应混合精度开启
  USE_CHECKPOINT: True # 【核心瘦身】开启梯度检查点，用时间换空间，省出一半显存！
  ACCUMULATION_STEPS: 4 # 因为 Batch Size 变成了1，我们累加 4 次梯度再更新，等效于 Batch Size = 4